
name = "esencia"
compatibility_date = "2025-03-12"

# Define the entry point for the Worker
main = "dist/worker.js"

[build]
command = "node cloudflare-build.js"

[site]
bucket = "./dist"

[dev]
port = 8787

# For Pages deployment
[env.production]
vars = { ENVIRONMENT = "production" }
