
name = "vibrant-web-muse"
compatibility_date = "2025-03-12"

# Define the entry point for the Worker
main = "dist/worker.js"

[build]
command = "npm run build && node cloudflare-worker.js"

[site]
bucket = "./dist"

[dev]
port = 8787
