name = "vibrant-web-muse"
compatibility_date = "2025-03-12"  # Use today's date

# Define the entry point for the Worker
main = "dist/index.js"  # Change this if your entry file is in a different location

[build]
command = "npm run build"  # Change to "bun build" if using Bun
watch_dir = "src"

[site]
bucket = "./dist"  # Set this to your build output directory

[dev]
port = 8787

main = "dist/index.js"  # Change this based on your project's build output

